services:
  postgres:
    image: postgres:17-alpine
    container_name: pg_todo
    restart: always
    env_file:
      - .env
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: