#!/usr/bin/env just --justfile

@a_default:
    just --list

@dev:
    uv run uvicorn app.main:app --reload

@db:
    uv run psql -h localhost -p 5433 -U postgres -d box

@makemigrations name:
    uv run alembic revision --autogenerate -m "{{name}}"

@migrate:
    uv run alembic upgrade head

@migrate_down steps:
    uv run alembic downgrade -{{steps}}