#!/usr/bin/env just --justfile

@a_default:
    just --list

dev:
    uv run uvicorn app.main:app --reload --log-config log.conf.yaml

@db:
    uv run psql -h localhost -p 5433 -U postgres -d kg

@makemigrations name:
    uv run alembic revision --autogenerate -m "{{name}}"

@migrate:
    uv run alembic upgrade head

@migrate_down steps:
    uv run alembic downgrade -{{steps}}

@lint:
    uv run ruff check --fix

@format:
    uv run ruff format